## workflows/deploy.yml
name: Deploy Pages

on:
  push:
    branches:
      - main # 这里只配置了main分支，所以只有推送main分支才会触发以下任务

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.16.0
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build:prod
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          folder: dist
